name: AWS DEPLOY TO STAGING
# turn off deploy to AWS
#Temporrary text here for testing deployment
on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PW: ${{ secrets.DB_PW}}
      DB_USER: ${{ secrets.DB_USER }}
      DB_NAME: ${{ secrets.DB_NAME }}
      CLIENT_ID: ${{secrets.CLIENT_ID}}
      CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
      PORT: ${{secrets.PORT}}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: dev
      - uses: actions/setup-node@v5
        with:
          node-version: 
      - run: npm install

      - run: |
          touch .env
          echo DB_HOST = "$DB_HOST" >> .env
          echo DB_PW = "$DB_PW" >> .env
          echo DB_USER = "$DB_USER" >> .env
          echo DB_NAME = "$DB_NAME" >> .env
          echo CLIENT_ID = "$CLIENT_ID" >> .env
          echo CLIENT_SECRET = "$CLIENT_SECRET" >> .env
           echo PORT = "$PORT" >> .env

      - run: npm run bundle

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "deploy/"
          REMOTE_HOST: "workerscheduling.eaglesoftwareteam.com"
          REMOTE_USER: ubuntu
          TARGET: "nodeapps/sev2026/t4"
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        env:
          NAME: "Root"
        with:
          hosts: "ubuntu@workerscheduling.eaglesoftwareteam.com"
          privateKey: ${{ secrets.SERVER_SSH_KEY }}
          debug: false
          command: |
            cd nodeapps/sev2026/t4
            npm install
            sudo systemctl stop workerscheduling-t4-backend
            sudo cp workerscheduling-t4-backend.service /lib/systemd/system/workerscheduling-t4-backend.service
            sudo systemctl daemon-reload
            sudo systemctl start workerscheduling-t4-backend
